name: insite
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^1.0.1
  build_runner: ^1.10.11
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  equatable: ^2.0.0
  flutter_svg: ^0.19.3
  flutter_webview_plugin: ^0.3.11
  get_it: ^7.1.3
  intl: ^0.17.0
  json_annotation: 3.1.1
  liquid_progress_indicator: ^0.3.2
  logger: ^1.0.0
  responsive_builder: ^0.4.1
  retrofit: ^1.2.0
  shared_preferences: ^2.0.5
  stacked: ^2.1.7
  stacked_services: ^0.7.3
  google_maps_flutter: ^2.0.3
  table_calendar: ^3.0.0
  clippy_flutter: ^1.1.1
  custom_info_window: ^1.0.1
  percent_indicator: ^3.0.1
  charts_flutter: ^0.10.0
  google_maps_cluster_manager: ^1.0.0
  syncfusion_flutter_gauges: ^19.1.65
  syncfusion_flutter_charts: ^19.1.65

  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  quiver: ^2.1.5
  dependencies:
  syncfusion_flutter_calendar: ^19.1.69
  badges: ^1.2.0
  flutter_map: ^0.12.0
  flutter_map_marker_cluster: ^0.3.5 # or the latest version on Pub
  fluttertoast: ^7.1.8
  graphql_flutter: any
  oauth2: ^1.6.3
  package_info: ^2.0.2
  crypto: ^2.1.4
  random_string: ^2.0.1
  load: ^1.0.0
  geocore: ^0.7.0
  google_polyline_algorithm: ^3.1.0
  polyline: ^1.0.2
  google_maps_controller: ^1.1.0
  flutter_colorpicker: ^0.3.5
  form_field_validator: ^1.1.0
  excel: ^1.1.5
  file_picker: any
  permission_handler: ^5.1.0+2
  path_provider: any
  flutter_downloader: ^1.5.1
  
  
  


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  retrofit_generator: any
  hive_generator: ^0.8.2
  
 
flutter:
  uses-material-design: true

  assets:
    - assets/images/add.svg
    - assets/images/edit.svg

    - assets/images/searchs.svg
    - assets/images/dummy.png
    - assets/images/menubar.svg
    - assets/images/searchs.svg
    - assets/images/clock.svg
    - assets/images/truck.svg
    - assets/images/supportmanager.svg
    - assets/images/assetmanager.svg
    - assets/images/location.svg
    - assets/images/health.svg
    - assets/images/van.svg
    - assets/images/maint.svg
    - assets/images/admin.svg
    - assets/images/plant.svg
    - assets/images/sub.svg
    - assets/images/noti.svg
    - assets/images/arrowdown.svg
    - assets/images/filter.svg
    - assets/images/hitachi.png
    - assets/images/truck.png
    - assets/images/menu.svg
    - assets/images/plus.svg
    - assets/images/minus.svg
    - assets/images/marker.png
    - assets/images/arrows.png
    - assets/images/mapclose.png
    - assets/images/EX70.png
    - assets/images/EX130.png
    - assets/images/EX200.png
    - assets/images/EX210.png
    - assets/images/EX210LC.png
    - assets/images/shinrai.png
    - assets/images/TH86.png
    - assets/images/TL340H.png
    - assets/images/cap.png
    - assets/images/layer_tata.png
    - assets/images/jcp_login.png
    - assets/images/crane_small_login.png
    - assets/images/crane_large_login.png
    - assets/images/tractor_login.png
    - assets/images/lorry_login.png
    - assets/images/lorry_large_login.png
    - assets/images/hitachi_font.png
    - assets/images/font_login.png
    - assets/images/fault_world.png
    - assets/images/users.svg
    - assets/images/gear_icon.svg
    - assets/images/geofence.svg
    - assets/images/reports.svg
    - assets/images/delete_icon.svg
    - assets/images/add_user_icon_one.png
    - assets/images/add_user_icon_two.png
    - assets/images/add_user_icon_three.png
    - assets/images/ic_trimble_logo.png
    - assets/images/ic_eol_launcher.png
    - assets/images/trimble.svg
    - assets/images/delete.svg
    - assets/images/dashboard.svg
    - assets/images/path0.svg
    - assets/images/flet.svg
    - assets/images/sms.svg
    - assets/images/export.svg
    - assets/images/transfer.svg
    - assets/images/hier.svg
    - assets/images/message.svg
    - assets/images/warning.svg
    - assets/images/users_items.svg
    - assets/images/assessment.svg
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Light.ttf
