name: insite
description: A new Flutter project.
publish_to: none
version: 2.1.7+230
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  badges: ^3.0.2
  build_runner: ^2.1.2
  charts_flutter: ^0.12.0
  clippy_flutter: ^2.0.0-nullsafety.0
  cookie_jar: ^3.0.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.0
  custom_info_window: ^1.0.1
  dio: ^5.0.3
  dio_cookie_manager: ^2.0.0
  easy_localization: ^3.0.0
  equatable: ^2.0.0
  excel: ^2.0.0-null-safety
  file_picker: ^4.2.7
  firebase_core: ^2.8.0
  firebase_core_platform_interface: ^4.5.3
  firebase_crashlytics: ^3.0.17
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.2
  #flutter_downloader: ^1.5.1
  flutter_map_marker_cluster: ^0.5.0
  flutter_svg: ^2.0.4
  flutter_typeahead: ^4.0.0
  flutter_webview_plugin: ^0.4.0
  fluttertoast: ^8.0.8
  form_field_validator: ^1.1.0
  geobase: ^0.3.2
  geocore: ^0.10.1
  geodesy: ^0.4.0-nullsafety.0
  geolocator: ^8.2.1
  get_it: ^7.1.3
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_controller: ^1.1.0
  google_maps_flutter: ^2.1.1
  google_polyline_algorithm: ^3.1.0
  gql_dio_link: ^0.3.0
  graphql_flutter: ^5.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  #horizontal_data_table: any
  in_app_update: ^4.0.1
  intl: ^0.17.0
  json_annotation: ^4.1.0
  jwt_decoder: ^2.0.1
  liquid_progress_indicator: ^0.4.0
  load: ^1.0.0
  location: ^4.4.0
  logger: ^1.0.0
  maps_toolkit: ^2.0.0
  oauth2: ^2.0.0

  package_info: ^2.0.2
  package_info_plus: any
  path_provider: ^2.0.4
  percent_indicator: ^4.2.3
  permission_handler: ^8.1.6
  phone_number: ^1.0.0
  point_in_polygon: ^1.0.0
  quiver: ^3.0.0
  random_string: ^2.0.1
  responsive_builder: ^0.4.1
  retrofit: ^4.0.1
  shared_preferences: ^2.0.5
  stacked: ^2.1.7
  stacked_services: ^0.9.9
  syncfusion_flutter_calendar: ^20.4.54
  syncfusion_flutter_charts: ^20.4.54
  syncfusion_flutter_gauges: ^20.4.54
  table_calendar: ^3.0.0
  timezone: ^0.9.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/add.svg
    - assets/images/edit.svg
    - assets/images/searchs.svg
    - assets/images/dummy.png
    - assets/images/menubar.svg
    - assets/images/searchs.svg
    - assets/images/clock.svg
    - assets/images/truck.svg
    - assets/images/supportmanager.svg
    - assets/images/assetmanager.svg
    - assets/images/location.svg
    - assets/images/health.svg
    - assets/images/van.svg
    - assets/images/maint.svg
    - assets/images/admin.svg
    - assets/images/plant.svg
    - assets/images/sub.svg
    - assets/images/noti.svg
    - assets/images/arrowdown.svg
    - assets/images/filter.svg
    - assets/images/hitachi.png
    - assets/images/truck.png
    - assets/images/menu.svg
    - assets/images/plus.svg
    - assets/images/minus.svg
    - assets/images/marker.png
    - assets/images/arrows.png
    - assets/images/mapclose.png
    - assets/images/EX70.png
    - assets/images/EX130.png
    - assets/images/EX200.png
    - assets/images/EX210.png
    - assets/images/EX210LC.png
    - assets/images/shinrai.png
    - assets/images/TH86.png
    - assets/images/TL340H.png
    - assets/images/cap.png
    - assets/images/layer_tata.png
    - assets/images/jcp_login.png
    - assets/images/crane_small_login.png
    - assets/images/crane_large_login.png
    - assets/images/tractor_login.png
    - assets/images/lorry_login.png
    - assets/images/lorry_large_login.png
    - assets/images/hitachi_font.png
    - assets/images/font_login.png
    - assets/images/fault_world.png
    - assets/images/users.svg
    - assets/images/gear_icon.svg
    - assets/images/geofence.svg
    - assets/images/reports.svg
    - assets/images/delete_icon.svg
    - assets/images/add_user_icon_one.png
    - assets/images/add_user_icon_two.png
    - assets/images/add_user_icon_three.png
    - assets/images/ic_trimble_logo.png
    - assets/images/ic_eol_launcher.png
    - assets/images/trimble.svg
    - assets/images/delete.svg
    - assets/images/dashboard.svg
    - assets/images/path0.svg
    - assets/images/flet.svg
    - assets/images/sms.svg
    - assets/images/export.svg
    - assets/images/transfer.svg
    - assets/images/hier.svg
    - assets/images/message.svg
    - assets/images/warning.svg
    - assets/images/users_items.svg
    - assets/images/assessment.svg
    - assets/images/descending_filter_group.png
    - assets/images/ascending_filter_group.png
    - assets/images/10001.png
    - assets/images/10002.png
    - assets/images/0.png
    - assets/images/excavator.png
    - assets/images/wheel_loader.png
    - assets/images/backhoe_loader.png
    - assets/images/model/EX70.png
    - assets/images/model/EX110.png
    - assets/images/model/EX130.png
    - assets/images/model/EX200.png
    - assets/images/model/EX210.png
    - assets/images/model/EX210LC.png
    - assets/images/model/SHINRAI.png
    - assets/images/model/TH76.png
    - assets/images/model/TH86.png
    - assets/images/model/TL340H.png
    - assets/images/model/TL360Z.png
    - assets/images/model/TMX20.png
    - assets/images/maintenance.svg
    - assets/images/invert.svg
    - assets/images/dashboardicon.svg
    - assets/images/fleeticon.svg
    - assets/images/utilizationicon.svg
    - assets/images/maintenanceicon.svg
    - assets/images/healthicon.svg
    - assets/images/asset_operationicon.svg
    - assets/images/adminisitratoricon.svg
    - assets/images/worksiq.png
    - assets/images/ic_fleet.png
    - assets/images/health_icon.png
    - assets/images/ic_admin-setting-icon.png
    - assets/images/worksiq.svg
    - assets/images/worksiq.png
    - assets/images/cummins-logo.png
    - assets/images/locationIcon.svg
    - assets/images/assetOperationIcon.svg
    - assets/images/utilisationIcon.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Light.ttf
